# Generated by Django 2.2.3 on 2019-11-21 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(default=0)),
                ('fecha', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('cantidad', models.IntegerField()),
                ('precio_unit', models.FloatField()),
                ('monto', models.FloatField()),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(default=0)),
                ('fecha', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('cantidad', models.IntegerField()),
                ('precio_unit', models.FloatField()),
                ('monto', models.FloatField()),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
