# Generated by Django 2.2.3 on 2019-11-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='existencias',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
