# Generated by Django 2.2.3 on 2019-11-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_materia_existencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='existencias',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
