# Generated by Django 2.2.3 on 2019-11-21 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codigo', models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9)])),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('salario', models.FloatField()),
                ('isss', models.FloatField()),
                ('renta', models.FloatField()),
                ('afp', models.FloatField()),
                ('sal_neto', models.FloatField()),
            ],
            options={
                'ordering': ('-codigo',),
            },
        ),
    ]
