# Generated by Django 2.2.3 on 2019-11-23 19:59
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='apellidos',
            new_name='puesto',
        ),
        migrations.AddField(
            model_name='empleado',
            name='desc',
            field=models.FloatField(default='0.00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha',
            field=models.DateField(default='2019-12-31'),
            preserve_default=False,
        ),
    ]
