# Generated by Django 2.2.3 on 2019-11-21 16:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('nombre', models.CharField(max_length=35)),
                ('codigo', models.CharField(blank=True, max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(4)])),
                ('debe', models.FloatField(default=0.0)),
                ('haber', models.FloatField(default=0.0)),
                ('saldo', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('nombre', models.CharField(max_length=35)),
                ('codigo', models.CharField(max_length=1, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(1)])),
                ('debe', models.FloatField(default=0.0)),
                ('haber', models.FloatField(default=0.0)),
                ('saldo', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='SubCuenta',
            fields=[
                ('nombre', models.CharField(max_length=35)),
                ('codigo', models.CharField(blank=True, max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(6)])),
                ('debe', models.FloatField(default=0.0)),
                ('haber', models.FloatField(default=0.0)),
                ('saldo', models.FloatField(default=0.0)),
                ('padre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.Cuenta')),
            ],
            options={
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('nombre', models.CharField(max_length=35)),
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(2)])),
                ('debe', models.FloatField(default=0.0)),
                ('haber', models.FloatField(default=0.0)),
                ('saldo', models.FloatField(default=0.0)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.Tipo')),
            ],
            options={
                'ordering': ('codigo',),
            },
        ),
        migrations.AddField(
            model_name='cuenta',
            name='rubro',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.Rubro'),
        ),
    ]
